SRC_NAME = vntcli
THISDIR = $(shell pwd)

all: 

config_test:

configure:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/vnt-cli /usr/bin/vnt-cli
	$(ROMFSINST) -p +x $(THISDIR)/vnt.sh /usr/bin/vnt.sh
	$(ROMFSINST) -p +x $(THISDIR)/hxzn.sh /usr/bin/hxzn.sh
